default_language_version:
    python: python3.9.7
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: venv
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-docstring-first
    - id: check-json
    - id: check-yaml
    - id: check-ast
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
            "--disable=C",
            "--disable=C0415",
            "--disable=W",
            "--disable=R0903",
            "--disable=E1101",
            "--msg-template={path}||{msg_id}||{symbol}||{category}||{line}||{column}||{msg}",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=1.9.1]
