version: "3"

services:
#  sql_db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - "8901:5432"
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=172.18.0.2
#      - POSTGRES_PORT=5432

  backend:
    entrypoint: sh start.sh
    restart: always
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    hostname: backend
#    links:
#      - sql_db
#    depends_on:
#      - sql_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=172.18.0.2
      - POSTGRES_PORT=5432
      - ENV=${ENV}
      - LOCAL_PORT=${LOCAL_PORT}
      - DOCUMENTATION=${DOCUMENTATION}
      - M3O_API_TOKEN=${M3O_API_TOKEN}
    volumes:
      - ./storage:/storage
