version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /opt/mongo/data:/data/db
    restart: always

  backend:
    entrypoint: hypercorn -k uvloop --bind="0.0.0.0:8080" --debug --reload main
    restart: always
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    hostname: backend
    links:
      - mongodb
    depends_on:
      - mongodb

    volumes:
      - ./storage:/storage
