# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Fast Tests

on:
  push:
    branches: [ "develop", "master", "main" ]
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - uses: Gr1N/setup-poetry@v7
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    - run: poetry --version
    - name: Install dependencies
      run: |
        poetry install -vvv
    - name: Run fast tests with pytest
      run: |
        poetry run pytest -m fast tests
